// <auto-generated />
using System;
using CinematicketBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cinematicketBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016112940_updateseanse")]
    partial class updateseanse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinematicketBackend.Models.Seans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Godzina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypSeansu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WiekMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seanse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:30",
                            Miejscowosc = "Legnica",
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:30",
                            Miejscowosc = "Legnica",
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:15",
                            Miejscowosc = "Lubin",
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Lubin",
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        });
                });

            modelBuilder.Entity("cinematicketBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
