// <auto-generated />
using System;
using CinematicketBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cinematicketBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinematicketBackend.Models.Bilet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumerMiejsca")
                        .HasColumnType("int");

                    b.Property<int>("SeansId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeansId");

                    b.HasIndex("UserId");

                    b.ToTable("Bilety");
                });

            modelBuilder.Entity("CinematicketBackend.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sale");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LiczbaMiejsc = 100,
                            Nazwa = "Sala 1"
                        },
                        new
                        {
                            Id = 2,
                            LiczbaMiejsc = 100,
                            Nazwa = "Sala 2"
                        },
                        new
                        {
                            Id = 3,
                            LiczbaMiejsc = 100,
                            Nazwa = "Sala 3"
                        });
                });

            modelBuilder.Entity("CinematicketBackend.Models.Seans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Godzina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejscowosc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("TypSeansu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WiekMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Seanse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:30",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:30",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:15",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Legnica",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 6,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:00",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 7,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:00",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 8,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:30",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 9,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 10,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "20:30",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 11,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 12,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "19:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 13,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 14,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 15,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 16,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 17,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 18,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 19,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 20,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 21,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 22,
                            Data = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "19:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 23,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:30",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 24,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:30",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 25,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:15",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 26,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 27,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 28,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:00",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 29,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:00",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 30,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:30",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 31,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 32,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "20:30",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 33,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 34,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "19:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 35,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 36,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 37,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 38,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 39,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 40,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 41,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 42,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 43,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 44,
                            Data = new DateTime(2025, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "19:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 45,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:30",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 46,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:30",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 47,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:15",
                            Miejscowosc = "Legnica",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 48,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 49,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Legnica",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 50,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:00",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 51,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:00",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 52,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:30",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 53,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 54,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "20:30",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 55,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 56,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "19:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 57,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 58,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 59,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 60,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 61,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 62,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 63,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 64,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 65,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 66,
                            Data = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "19:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 67,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:30",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 68,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:30",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 69,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:15",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 70,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 71,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 72,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:00",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 73,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:00",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 74,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:30",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 75,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:00",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 76,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "20:30",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 77,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 78,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "19:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 79,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 80,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 81,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 82,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 83,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 84,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 85,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 86,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "18:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 87,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "21:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 88,
                            Data = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "19:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 89,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:00",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 90,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:15",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 91,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:45",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 92,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:15",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 93,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:15",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 94,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "20:00",
                            Miejscowosc = "Legnica",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 95,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:15",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 96,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:00",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 97,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:30",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 98,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:45",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 99,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:00",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 100,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "20:30",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 101,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 102,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:15",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 103,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 104,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:15",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 105,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 106,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 107,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:45",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 108,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 109,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 110,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 111,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 112,
                            Data = new DateTime(2025, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:45",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 113,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:00",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 114,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:15",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 115,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:45",
                            Miejscowosc = "Legnica",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 116,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:15",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 117,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:15",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 118,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "20:00",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 119,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:15",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 120,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:00",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 121,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:30",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 122,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:45",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 123,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:00",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 124,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "20:30",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 125,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 126,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:15",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 127,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 128,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:15",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 129,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 130,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 131,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:45",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 132,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "21:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 133,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 134,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 135,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 136,
                            Data = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:45",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 137,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:00",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 138,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:15",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 139,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:45",
                            Miejscowosc = "Legnica",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 140,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:15",
                            Miejscowosc = "Legnica",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 141,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:30",
                            Miejscowosc = "Legnica",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 142,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "19:45",
                            Miejscowosc = "Legnica",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 143,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "17:15",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 144,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:00",
                            Miejscowosc = "Lubin",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 145,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:30",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 146,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:45",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 147,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:00",
                            Miejscowosc = "Lubin",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 148,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "19:30",
                            Miejscowosc = "Lubin",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 149,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 150,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:15",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 151,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "14:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 152,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "16:15",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 153,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "18:30",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 154,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:00",
                            Miejscowosc = "Wrocław (Aleja Bielany)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 155,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "16:45",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 1,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 156,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Thriller / Musical",
                            Godzina = "20:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Joker: Folie à Deux",
                            WiekMin = 15
                        },
                        new
                        {
                            Id = 157,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "15:00",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 158,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Animacja / Przygodowy",
                            Godzina = "17:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Dubbing",
                            Tytul = "Vaiana 2",
                            WiekMin = 0
                        },
                        new
                        {
                            Id = 159,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Komedia / Fantasy",
                            Godzina = "19:30",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 2,
                            TypSeansu = "Napisy",
                            Tytul = "Beetlejuice Beetlejuice",
                            WiekMin = 13
                        },
                        new
                        {
                            Id = 160,
                            Data = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gatunek = "Akcja / Dramat",
                            Godzina = "18:15",
                            Miejscowosc = "Wrocław (Magnolia Park)",
                            SalaId = 3,
                            TypSeansu = "Napisy",
                            Tytul = "Gladiator 2",
                            WiekMin = 15
                        });
                });

            modelBuilder.Entity("cinematicketBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CinematicketBackend.Models.Bilet", b =>
                {
                    b.HasOne("CinematicketBackend.Models.Seans", "Seans")
                        .WithMany()
                        .HasForeignKey("SeansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cinematicketBackend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seans");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinematicketBackend.Models.Seans", b =>
                {
                    b.HasOne("CinematicketBackend.Models.Sala", "Sala")
                        .WithMany("Seanse")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("CinematicketBackend.Models.Sala", b =>
                {
                    b.Navigation("Seanse");
                });
#pragma warning restore 612, 618
        }
    }
}
